name: test workflow

on:
  repository_dispatch:
    types: [test_run]
  workflow_dispatch:
    inputs:
      workflow_run_name:
        description: 'test'
        default: ''
        required: false
        type: string

jobs:
  create_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Test
        run: echo "ok"
        
        
