name: test workflow

on:
  repository_dispatch:
    types: [test_run]
  workflow_dispatch:

jobs:
  create_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Test
        run: echo "ok"
        
        
